import {chromium,expect} from '@playwright/test';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {writeZip,readZip} from '../../src/zip.mjs';
import {loadBundle} from '../../src/bundle.mjs';
const artifacts=resolve('artifacts/browser');await mkdir(artifacts,{recursive:true});
const report={passed:false,cases:[],screenshots:[],pageErrors:[],externalRequests:[]};
const check=(name,details={})=>{report.cases.push({name,passed:true,...details});console.log('PASS',name);};
const executable=process.env.CHROMIUM_PATH;if(!executable)throw Error('CHROMIUM_PATH is required; use the hosted sandboxed browser');
const browser=await chromium.launch({executablePath:executable,headless:true,chromiumSandbox:true});
report.browserVersion=browser.version();report.chromiumSandboxRequested=true;
const commands=execFileSync('ps',['-eo','args'],{encoding:'utf8'}).split('\n').filter(s=>s.includes('--remote-debugging-pipe')&&s.includes('--user-data-dir=')&&s.includes('chrome'));
if(!commands.length||commands.some(s=>s.includes('--no-sandbox')))throw Error('Sandboxed Chrome process could not be established');
report.sandboxCommandVerified=true;
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();page.on('pageerror',error=>report.pageErrors.push(error.message));page.on('request',request=>{if(/^https?:/.test(request.url()))report.externalRequests.push(request.url());});
const fileURL=pathToFileURL(resolve('dist/exposure-grid.html')).href;
const notice=()=>page.locator('#status');
async function ready(){await expect(page.locator('#review')).toBeVisible();await expect(page.locator('#export-zip')).not.toHaveText(/作成しています|building a ZIP/);}
async function screenshot(name,fullPage=true){await page.screenshot({path:resolve(artifacts,name),fullPage});report.screenshots.push(name);}
async function fixtureEntries(base='source'){const entries=[{name:`${base}.csv`,data:new Uint8Array(await readFile(`fixtures/${base}.csv`))}];for(const name of await readdir(`fixtures/${base}.frames`))entries.push({name:`${base}.frames/${name}`,data:new Uint8Array(await readFile(`fixtures/${base}.frames/${name}`))});return entries;}
async function setZIP(name,entries){await page.locator('#zip-input').setInputFiles({name,mimeType:'application/zip',buffer:Buffer.from(writeZip(entries))});}
async function download(base,keyboard=false){const wait=page.waitForEvent('download');if(keyboard){await page.locator('#export-zip').focus();await page.keyboard.press('Enter');}else await page.locator('#export-zip').click();const received=await wait;expect(received.suggestedFilename()).toBe(base+'.zip');await received.saveAs(resolve(artifacts,base+'.zip'));const bytes=new Uint8Array(await readFile(resolve(artifacts,base+'.zip')));const entries=await readZip(bytes);const parsed=await loadBundle(entries);return {bytes,entries,parsed};}
try{
 await page.goto(fileURL);await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#empty-state')).toBeVisible();await expect(page.locator('#export-zip')).toBeDisabled();await screenshot('01-ja-empty-desktop.png');check('Offline file loads in Japanese with export blocked until a valid project');
 await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();check('Keyboard skip link moves focus to workspace');
 await page.locator('#sample-exact').click();await ready();await expect(page.locator('#source-info')).toContainText('12 FPS');await expect(page.locator('#metrics')).toContainText('48');await expect(page.locator('#ack-wrap')).toBeHidden();await expect(page.locator('#export-zip')).toBeEnabled();await expect(page.locator('#boundary-body tr')).toHaveCount(7);await screenshot('02-ja-exact-desktop.png');
 const exact=await download('retimed24');expect(exact.parsed.project.fps).toBe(24);expect(exact.parsed.project.frameCount).toBe(48);const pins=JSON.parse(await readFile('fixtures/png-sha256.json','utf8'));for(const [name,data] of exact.parsed.project.images)expect(createHash('sha256').update(data).digest('hex')).toBe(pins[name]);check('Actual exact download preserves all five image hashes and48frames',{zipBytes:exact.bytes.length,sha256:createHash('sha256').update(exact.bytes).digest('hex')});
 await page.locator('#lang-en').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('#target-fps')).toHaveValue('24');await expect(page.locator('#export-zip')).toBeEnabled();await screenshot('03-en-exact-desktop.png');check('Language switch preserves source, settings and valid review');
 const beforeCancel=await page.locator('#source-info').textContent();const chooserPromise=page.waitForEvent('filechooser');await page.locator('#zip-input').click();const chooser=await chooserPromise;await chooser.setFiles([]);await expect(page.locator('#source-info')).toHaveText(beforeCancel);await expect(page.locator('#export-zip')).toBeEnabled();check('Cancelled file selection preserves existing reviewed work');
 await page.locator('#sample-rounded').click();await ready();await expect(page.locator('#mode')).toHaveValue('rounded');await expect(page.locator('#metrics')).toContainText('+1/60 s');await expect(page.locator('#rounding-ack')).not.toBeChecked();await expect(page.locator('#export-zip')).toBeDisabled();await expect(page.locator('#boundary-body')).toContainText('-1/120 s');await expect(page.locator('#boundary-body')).toContainText('+1/60 s');await screenshot('04-en-rounded-review.png');
 await page.locator('#mode').selectOption('exact');await expect(page.locator('#review')).toBeHidden();await expect(notice()).toContainText('Exact conversion is not possible');await expect(page.locator('#export-zip')).toBeDisabled();await page.locator('#mode').selectOption('rounded');await ready();await expect(page.locator('#rounding-ack')).not.toBeChecked();await page.locator('#rounding-ack').focus();await page.keyboard.press('Space');await expect(page.locator('#rounding-ack')).toBeChecked();await expect(page.locator('#export-zip')).toBeEnabled();const rounded=await download('rounded30',true);expect(rounded.parsed.project.frameCount).toBe(8);expect(rounded.parsed.project.fps).toBe(30);const receipt=JSON.parse(new TextDecoder().decode(rounded.entries.find(e=>e.name==='rounded30.review.json').data));expect(receipt.durationErrorSeconds).toEqual({numerator:1,denominator:60});check('Rounded mode discloses every rational error and duration, requires acknowledgment, exact mode refuses',{zipBytes:rounded.bytes.length,sha256:createHash('sha256').update(rounded.bytes).digest('hex')});await page.locator('#output-name').fill('rounded30-review');await expect(page.locator('#rounding-ack')).not.toBeChecked();await expect(page.locator('#export-zip')).toBeDisabled();check('Changing the reviewed output invalidates prior rounding acknowledgment');
 await page.locator('#sample-exact').click();await ready();await page.locator('#mode').selectOption('rounded');await page.locator('#target-fps').fill('1');await expect(page.locator('#review')).toBeHidden();await expect(notice()).toContainText('would disappear');await expect(page.locator('#export-zip')).toBeDisabled();check('Downsampling collision blocks the whole export');
 await page.locator('#sample-exact').click();await ready();await page.locator('#output-name').fill('../unsafe');await expect(page.locator('#name-error')).toBeVisible();await expect(page.locator('#export-zip')).toBeDisabled();await page.locator('#output-name').fill('safe-name');await expect(page.locator('#export-zip')).toBeEnabled();check('Unsafe output names cannot be exported');
 const missing=await fixtureEntries();missing.splice(1,1);await setZIP('missing.zip',missing);await expect(notice()).toContainText('Missing exact image');await expect(page.locator('#export-zip')).toBeDisabled();await expect(page.locator('#source-info')).toBeHidden();check('Missing-image import clears old result instead of exporting stale data');
 await page.locator('#zip-input').setInputFiles({name:'broken.zip',mimeType:'application/zip',buffer:Buffer.from('not a zip')});await expect(notice()).toContainText('Import stopped');await expect(page.locator('#export-zip')).toBeDisabled();check('Malformed archive remains blocked');
 await page.locator('#sample-exact').click();await ready();await setZIP('roundtrip.zip',exact.entries);await ready();await expect(page.locator('#source-info')).toContainText('24 FPS');await expect(notice()).toContainText('previous receipt');check('Actual exported bundle round-trips with a verified matching receipt');
 const changedReceipt=exact.entries.map(e=>({name:e.name,data:new Uint8Array(e.data)}));const receiptEntry=changedReceipt.find(e=>e.name.endsWith('.review.json'));const badReceipt=JSON.parse(new TextDecoder().decode(receiptEntry.data));badReceipt.targetFrames=47;receiptEntry.data=new TextEncoder().encode(JSON.stringify(badReceipt));await setZIP('tampered.zip',changedReceipt);await expect(notice()).toContainText('receipt does not match');await expect(page.locator('#export-zip')).toBeDisabled();check('Tampered companion receipt is rejected');
 await page.locator('#sample-exact').click();await ready();await page.evaluate(()=>{window.__originalDecompressionStream=window.DecompressionStream;window.DecompressionStream=class{constructor(format){const original=new window.__originalDecompressionStream(format);return {writable:original.writable,readable:original.readable.pipeThrough(new TransformStream({async transform(chunk,controller){await new Promise(resolve=>setTimeout(resolve,120));controller.enqueue(chunk);}}))};}};});
 let staleDownloads=0;const onDownload=()=>staleDownloads++;page.on('download',onDownload);await page.locator('#export-zip').click();await expect(notice()).toContainText('frozen snapshot');await page.locator('#target-fps').fill('48');await expect(page.locator('#target-fps')).toBeFocused();await expect(page.locator('#metrics')).toContainText('96');await page.waitForTimeout(1500);expect(staleDownloads).toBe(0);await expect(notice()).not.toContainText('building a ZIP');page.off('download',onDownload);await page.evaluate(()=>window.DecompressionStream=window.__originalDecompressionStream);check('Editing timing during async export discards old download and clears busy state');
 await page.evaluate(()=>{window.__arrayBuffer=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name.startsWith('delayed'))await new Promise(resolve=>setTimeout(resolve,700));return window.__arrayBuffer.call(this);};});
 await setZIP('delayed.zip',await fixtureEntries());await expect(notice()).toContainText('Checking');await page.locator('#sample-rounded').click();await ready();await page.waitForTimeout(1000);await expect(page.locator('#source-info')).toContainText('24 FPS');await expect(page.locator('#target-fps')).toHaveValue('30');check('Late import cannot overwrite a newer sample and settings');
 await setZIP('delayed-clear.zip',await fixtureEntries());await expect(notice()).toContainText('Checking');await page.locator('#clear').click();await page.waitForTimeout(1000);await expect(page.locator('#source-info')).toBeHidden();await expect(page.locator('#review')).toBeHidden();await expect(page.locator('#export-zip')).toBeDisabled();await expect(notice()).toContainText('cleared');await page.evaluate(()=>File.prototype.arrayBuffer=window.__arrayBuffer);check('Clear cancels pending import without reviving old data');
 const many=await fixtureEntries();let csv=new TextDecoder().decode(many[0].data);const rows=csv.trimEnd().split(/\r?\n/);rows[2]=rows[2].replace('24, 2, 12.000000','160, 2, 12.000000');const imagesA=['A.png','B.png','C.png'],imagesB=['X.png','Y.png'];const frameRows=Array.from({length:160},(_,i)=>`#${String(i).padStart(5,'0')}, "${imagesA[i%3]}", "${imagesB[i%2]}"`);many[0].data=new TextEncoder().encode(rows.slice(0,7).join('\r\n')+'\r\n'+frameRows.join('\r\n')+'\r\n');await setZIP('many.zip',many);await ready();await expect(page.locator('#boundary-count')).toContainText('161');await expect(page.locator('#boundary-body tr')).toHaveCount(25);await expect(page.locator('.timeline .exposure')).toHaveCount(404);await expect(page.locator('.timeline .omitted')).toHaveCount(4);await expect(page.locator('#layer-list')).toContainText('first 100 exposures only');for(let i=0;i<6;i++)await page.locator('#page-next').click();await expect(page.locator('#boundary-body')).toContainText('Clip ending');await expect(page.locator('#page-next')).toBeDisabled();await page.locator('#output-name').fill('many-reviewed');await expect(page.locator('#page-label')).toContainText('7 / 7');await expect(page.locator('#boundary-body')).toContainText('Clip ending');await page.locator('#page-prev').click();await expect(page.locator('#page-label')).toContainText('6 / 7');check('Timeline DOM is bounded with explicit truncation; all161 boundaries and clip ending remain reachable');
 for(const language of ['ja','en']){await page.locator(`#lang-${language}`).click();for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('#sample-rounded').click();await ready();const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width+1);await screenshot(`05-${language}-rounded-${width}.png`);}}check('Japanese and English mobile layouts fit390px and320px without page overflow');
 await page.setViewportSize({width:1440,height:1000});await page.locator('#lang-ja').click();await page.locator('#sample-rounded').click();await ready();await screenshot('06-ja-rounded-desktop.png');
 const dev=await context.newPage();dev.on('pageerror',error=>report.pageErrors.push(error.message));await dev.goto('http://127.0.0.1:4173/index.html');await dev.locator('#sample-exact').click();await expect(dev.locator('#review')).toBeVisible();await dev.close();check('Development module entry and offline bundled entry both work');
 expect(report.pageErrors).toEqual([]);expect(report.externalRequests).toEqual([]);report.passed=true;
}finally{await writeFile(resolve(artifacts,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();}
console.log(`PASS ${report.cases.length} browser scenarios; actual downloaded packages saved for independent extraction and native consumption`);
