import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {loadProject,retimeProject,serializeProject,exportEntries,mapBoundary,parseCSV,safeBasename,validateImageDecoding,estimateCSVBytes,LIMITS} from '../src/core.mjs';
const fixture=()=>[{name:'source.csv',data:new Uint8Array(readFileSync('fixtures/source.csv'))},...readdirSync('fixtures/source.frames').map(n=>({name:`source.frames/${n}`,data:new Uint8Array(readFileSync(`fixtures/source.frames/${n}`))}))];
const source=()=>loadProject(fixture());
const mutateCSV=fn=>{const e=fixture();e[0].data=new TextEncoder().encode(fn(new TextDecoder().decode(e[0].data)));return e;};
const rejects=(fn,code)=>assert.throws(fn,e=>e.code===code);
test('official exporter-style whitespace and fixed decimal integer FPS',()=>{const p=source();assert.equal(p.fps,12);assert.equal(p.frameCount,24);assert.deepEqual(p.layers.map(l=>l.name),['Layer A','Layer B']);assert.deepEqual(p.layers[1].exposures,[{start:0,end:3,image:''},{start:3,end:9,image:'X.png'},{start:9,end:15,image:''},{start:15,end:24,image:'Y.png'}]);});
test('handwritten 12→24 timing oracle, including blanks and end',()=>{const p=retimeProject(source(),24);assert.equal(p.frameCount,48);assert.deepEqual(p.layers.map(l=>l.exposures.map(e=>[e.start,e.end,e.image])),[[[0,12,'A.png'],[12,24,'B.png'],[24,48,'C.png']],[[0,6,''],[6,18,'X.png'],[18,30,''],[30,48,'Y.png']]]);assert.deepEqual(p.receipt.durationErrorSeconds,{numerator:0,denominator:1});assert(p.receipt.boundaries.every(b=>b.errorSeconds.numerator===0));});
test('exact serialized export round-trips semantic rows and byte-identical PNGs',async()=>{const p=retimeProject(source(),24);const entries=await exportEntries(p,'retimed24');const q=loadProject(entries.filter(e=>!e.name.endsWith('.json')));assert.deepEqual(q.layers,p.layers);for(const [name,data] of q.images)assert.equal(createHash('sha256').update(data).digest('hex'),createHash('sha256').update(p.images.get(name)).digest('hex'));});
test('24→12 boundary 1 and 2 collision blocks, never merges or drops',()=>{const p=source();p.fps=24;p.layers[0].exposures=[{start:0,end:1,image:'A.png'},{start:1,end:2,image:'B.png'},{start:2,end:24,image:'C.png'}];rejects(()=>retimeProject(p,12,'rounded'),'COLLAPSED_EXPOSURE');});
test('rounded 24→30 six-frame clip has explicit +1/60 second duration error',()=>{const p=source();p.fps=24;p.frameCount=6;p.layers=p.layers.map((l,i)=>({...l,exposures:[{start:0,end:6,image:i?'X.png':'A.png'}]}));rejects(()=>retimeProject(p,30,'exact'),'NOT_EXACT');const out=retimeProject(p,30,'rounded');assert.equal(out.frameCount,8);assert.deepEqual(out.receipt.durationErrorSeconds,{numerator:1,denominator:60});assert.deepEqual(out.receipt.boundaries.at(-1).errorSeconds,{numerator:1,denominator:60});});
test('rounding uses half-up integer arithmetic',()=>{assert.equal(mapBoundary(1,24,12),1);assert.equal(mapBoundary(2,24,12),1);assert.equal(mapBoundary(3,24,12),2);});
test('identity mapping is exact for all integer FPS 1–120',()=>{for(let fps=1;fps<=120;fps++){const p=source();p.fps=fps;assert.deepEqual(retimeProject(p,fps).layers,p.layers);}});
test('reject fractional, exponent, zero, and out-of-range FPS',()=>{for(const fps of ['23.976','1e1','0','121','NaN'])assert.throws(()=>retimeProject(source(),fps));});
test('reject folder overrides and extra metadata',()=>{rejects(()=>loadProject(mutateCSV(s=>s.replace('#Visible','#Folder, "elsewhere"\r\n#Visible'))),'LAYER_HEADERS');rejects(()=>loadProject(mutateCSV(s=>s.replace('Field Mode','Unknown metadata'))),'PROFILE');});
test('reject unsupported opacity/blending/visibility and field modes',()=>{rejects(()=>loadProject(mutateCSV(s=>s.replace('#Density, 1.000000','#Density, 0.500000'))),'LAYER_PROFILE');rejects(()=>loadProject(mutateCSV(s=>s.replace('#Blending, "Color"','#Blending, "Multiply"'))),'LAYER_PROFILE');rejects(()=>loadProject(mutateCSV(s=>s.replace('#Visible, 1','#Visible, 0'))),'LAYER_PROFILE');rejects(()=>loadProject(mutateCSV(s=>s.replace('Progressive','Interlaced'))),'PROFILE');});
test('reject nonzero, skipped, duplicate, or malformed frame rows',()=>{for(const replacement of ['#00001','#00003','#wat'])rejects(()=>loadProject(mutateCSV(s=>s.replace('#00000',replacement))),'FRAME_ROWS');});
test('reject declared count mismatches',()=>{rejects(()=>loadProject(mutateCSV(s=>s.replace('16, 16, 24, 2','16, 16, 25, 2'))),'FRAME_COUNT');rejects(()=>loadProject(mutateCSV(s=>s.replace('16, 16, 24, 2','16, 16, 24, 3'))),'LAYER_HEADERS');});
test('reject entirely blank layer instead of allowing Krita to drop it',()=>{rejects(()=>loadProject(mutateCSV(s=>s.replaceAll('"X.png"','""').replaceAll('"Y.png"','""'))),'EMPTY_LAYER');});
test('reject path traversal, absolute paths, nested payloads and ambiguous duplicates',()=>{for(const name of ['../a.png','/a.png','source.frames/../a.png','C:/a.png','source.frames\\a.png']){const e=fixture();e.push({name,data:new Uint8Array(1)});rejects(()=>loadProject(e),'PATH');}const e=fixture();e.push({...e[1],name:e[1].name.toUpperCase()});rejects(()=>loadProject(e),'DUPLICATE');});
test('reject missing images, wrong-case image references, multiple CSVs and unreferenced assets',()=>{const e=fixture();e.splice(1,1);rejects(()=>loadProject(e),'MISSING_IMAGE');rejects(()=>loadProject(mutateCSV(s=>s.replaceAll('A.png','a.png'))),'MISSING_IMAGE');const two=fixture();two.push({...two[0],name:'other.csv'});rejects(()=>loadProject(two),'CSV_COUNT');const extra=fixture();extra.push({name:'note.txt',data:new Uint8Array(1)});rejects(()=>loadProject(extra),'EXTRA_FILE');});
test('reject incompatible PNG dimensions and wrong signature',()=>{const e=fixture();e[1].data[19]=17;rejects(()=>loadProject(e),'PNG_PROFILE');const x=fixture();x[1].data[0]=0;rejects(()=>loadProject(x),'PNG');});
test('CSV quote syntax is strict; quoted commas and quotes supported',()=>{assert.deepEqual(parseCSV('"a,b", "c""d",\n'),[['a,b','c"d','']]);for(const v of ['"unclosed','a"b,c','"x"y,z'])rejects(()=>parseCSV(v),'CSV_SYNTAX');});
test('safe Windows-compatible basenames only',()=>{for(const s of ['../x','CON','NUL.png','a/b','a\\b','x.','x ','','..','x:y'])assert.equal(safeBasename(s),false,s);assert.equal(safeBasename('Study 24fps'),true);});
test('receipt tracks signed boundary error separately from duration',()=>{const p=source();p.fps=24;const q=retimeProject(p,30,'rounded');assert.equal(q.receipt.durationErrorSeconds.numerator,0);assert(q.receipt.boundaries.some(x=>x.errorSeconds.numerator!==0));assert.equal(serializeProject(q).split('\r\n').length,38);});

test('reject damaged PNG chunk CRC instead of copying a corrupted cel',()=>{const e=fixture();e[1].data[e[1].data.length-1]^=1;rejects(()=>loadProject(e),'PNG');});

test('output suffixes stay inside basename length limits',async()=>{await assert.rejects(()=>exportEntries(retimeProject(source(),24),'x'.repeat(120)),e=>e.code==='PATH');assert.equal((await exportEntries(retimeProject(source(),24),'x'.repeat(108))).length,7);});

test('all original image streams validate without changing bytes',async()=>{assert.equal(await validateImageDecoding(source()),true);});

const crcPNG=data=>{let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;};
const pngChunk=(type,data)=>{const label=Buffer.from(type);const out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);label.copy(out,4);Buffer.from(data).copy(out,8);out.writeUInt32BE(crcPNG(Buffer.concat([label,data])),data.length+8);return out;};
const replaceIDAT=(bytes,payload)=>{const parts=[Buffer.from(bytes.slice(0,8))];const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let p=8;p<bytes.length;){const n=v.getUint32(p);const type=String.fromCharCode(...bytes.slice(p+4,p+8));parts.push(type==='IDAT'?pngChunk(type,payload):Buffer.from(bytes.slice(p,p+n+12)));p+=n+12;}return new Uint8Array(Buffer.concat(parts));};
test('export rejects CRC-correct but invalid or truncated zlib IDAT',async()=>{const entries=fixture();entries[1].data=replaceIDAT(entries[1].data,Buffer.from([0]));const p=loadProject(entries);await assert.rejects(()=>exportEntries(retimeProject(p,24),'broken'),e=>e.code==='PNG_DECODE');});
test('export bounds decompressed length and validates scanline filters',async()=>{const {deflateSync}=await import('node:zlib');for(const size of [1039,1041]){const entries=fixture();entries[1].data=replaceIDAT(entries[1].data,deflateSync(new Uint8Array(size)));await assert.rejects(()=>exportEntries(retimeProject(loadProject(entries),24),'bad'),e=>e.code==='PNG_DECODE');}const raw=new Uint8Array(1040);raw[0]=5;const e=fixture();e[1].data=replaceIDAT(e[1].data,deflateSync(raw));await assert.rejects(()=>exportEntries(retimeProject(loadProject(e),24),'filter'),e=>e.code==='PNG_DECODE');});
test('large declared images are blocked before decompression',async()=>{const p=source(),bytes=Buffer.from(p.images.get('A.png'));bytes.writeUInt32BE(16384,16);bytes.writeUInt32BE(16384,20);bytes.writeUInt32BE(crcPNG(bytes.subarray(12,29)),29);p.width=p.height=16384;p.images=new Map([['A.png',new Uint8Array(bytes)]]);await assert.rejects(()=>validateImageDecoding(p),e=>e.code==='DECODE_LIMIT');});
test('export snapshots all reviewed state and image bytes before asynchronous decoding',async()=>{const p=retimeProject(source(),24);const pending=exportEntries(p,'frozen');p.images.get('A.png')[0]=0;p.layers[0].name='Mutated during await';p.receipt.layers[0].name='Mutated receipt';p.frameCount=1;const entries=await pending;const image=entries.find(e=>e.name==='frozen.frames/A.png');assert.equal(image.data[0],137);const reloaded=loadProject(entries.filter(e=>!e.name.endsWith('.json')));assert.equal(reloaded.frameCount,48);assert.equal(reloaded.layers[0].name,'Layer A');const receipt=JSON.parse(new TextDecoder().decode(entries.at(-1).data));assert.equal(receipt.layers[0].name,'Layer A');});

test('projected CSV size is exact, including Unicode header text',()=>{const p=retimeProject(source(),24);p.name='日本語の作品';p.layers[0].name='Layer, "quoted"';assert.equal(estimateCSVBytes(p),new TextEncoder().encode(serializeProject(p)).length);});
test('long-reference upsampling is rejected before oversized CSV expansion',async()=>{const p=source(),imageA='A'.repeat(116)+'.png',imageB='B'.repeat(116)+'.png';p.images=new Map([[imageA,p.images.get('A.png')],[imageB,p.images.get('X.png')]]);p.frameCount=10000;p.layers[0].exposures=[{start:0,end:10000,image:imageA}];p.layers[1].exposures=[{start:0,end:10000,image:imageB}];const input=serializeProject(p);assert(new TextEncoder().encode(input).length<16*1024*1024);const q=retimeProject(p,120);assert.equal(q.frameCount,100000);assert(estimateCSVBytes(q)>16*1024*1024);await assert.rejects(()=>exportEntries(q,'too-large'),e=>e.code==='CSV_SIZE');assert.throws(()=>serializeProject(q),e=>e.code==='CSV_SIZE');});

test('total exposure complexity is bounded before building a huge receipt',()=>{const entries=fixture();let lines=new TextDecoder().decode(entries[0].data).trimEnd().split(/\r?\n/);lines[2]=lines[2].replace('24, 2, 12.000000','10001, 2, 12.000000');const frames=Array.from({length:10001},(_,i)=>`#${String(i).padStart(5,'0')}, "${['A.png','B.png','C.png'][i%3]}", "${['X.png','Y.png'][i%2]}"`);entries[0].data=new TextEncoder().encode(lines.slice(0,7).concat(frames).join('\r\n')+'\r\n');rejects(()=>loadProject(entries),'EXPOSURE_LIMIT');});
test('receipt is included in the output file-count limit',async()=>{const p=retimeProject(source(),24),bytes=p.images.get('A.png');p.images=new Map(Array.from({length:LIMITS.files-1},(_,i)=>[`cel${i}.png`,bytes]));await assert.rejects(()=>exportEntries(p,'too-many'),e=>e.code==='FILES');});
