import {readFile,writeFile,readdir} from 'node:fs/promises';
const samples={};
for(const [id,base] of [['exact','source'],['rounded','rounded-source']]){
 const entries=[{name:`${base}.csv`,base64:(await readFile(`fixtures/${base}.csv`)).toString('base64')}];
 for(const name of await readdir(`fixtures/${base}.frames`))entries.push({name:`${base}.frames/${name}`,base64:(await readFile(`fixtures/${base}.frames/${name}`)).toString('base64')});
 samples[id]=entries;
}
await writeFile('src/samples.mjs',`// Original fixture bytes, embedded for offline use. Generated by scripts/generate-samples.mjs.\nconst sampleData=${JSON.stringify(samples)};\nexport function sampleEntries(kind){return sampleData[kind].map(({name,base64})=>({name,data:Uint8Array.from(atob(base64),c=>c.charCodeAt(0))}));}\n`);
